### ISSUE TITLE
Support Redis Cluster

### ISSUE THREAD

**Issue by ph4r5h4d** [phalcon/phalcon#142]
Hi
As you know as of Redis 3 , this system support clustering and sharding in a way that a system can have redundant session and cache backend .

I checked Zephir codes of Redis backend cache and noticed Phalcon calls it using
`new Redis();`
new version of phpredis (Redis php driver) now supports clustering and array (not sure when they've added Redis array support but Redis cluster support is somehow new )
but they can't be called using normal `new Redis()` method and need to be called like these :

`$obj_cluster = new RedisCluster(NULL, Array('host:7000', 'host:7001', 'host:7003'));`
`$ra = new RedisArray(array("host1", "host2:63792", "host2:6380"));`

This way we will have HA redis cluster for backend cache and session (BTW the driver now supports session clustering and it can be done using php.ini , not tested by myself but i'll test it soon)

So it would be great if we can take advantage of Redis Cluster and Redist array natively in Phalcon .

**Comment by yergo** [comment]
I'm considering contributing to this issue. Got off track by missing RedisCluster adapter about... 7 years ago? It's crazy its not yet implemented. Is there a reason you are not implementing this? We don't have volounteers or there is a hidden issue in here?

**Comment by niden** [comment]
@yergo Lack of knowledge and volunteers. To get this going I will need to study on how the cluster works and then write the implementation. 

If you are interested in making an adapter for this, you can try it in the https://phalcon/phalcon repository first with a PHP implementation. Then it would be easy to port it to cphalcon. The Storage classes work just fine for `phalcon/phalcon`

**Comment by niden** [comment]
This has been resolved in #471

**Comment by borisdelev** [comment]
Appreciate your work @niden! Thank you!

**Comment by niden** [comment]
> Appreciate your work @niden! Thank you!

Thank you but the credit goes to @yergo who wrote the whole thing !!
