### ISSUE TITLE
Refactor Phalcon\Annotations

### ISSUE THREAD

**Issue by niden** [phalcon/phalcon#2]
Refactor Phalcon\Annotations

**Comment by jenovateurs** [comment]
I've started here: https://github.com/les-enovateurs/phalcon/tree/T2-annotations
But there is a C part so if someone is more expert than me, you can take this part.
I will be focused on other more simple Phalcon part.

**Comment by niden** [comment]
Resolved in https://github.com/phalcon/phalcon/pull/302
