### ISSUE TITLE
The received parameter is not being validated before storing it.

### ISSUE THREAD

**Issue by jeijei4** [phalcon/phalcon#220]
Phalcon\Storage\Serializer\Base64

https://github.com/phalcon/phalcon/blob/0884218231bd0c341d3bec6fa844009afdc3fbb6/src/Storage/Serializer/Base64.php#L52-L61

It seems to me that this should be the validation:
```php
/* 54 */    if (true !== is_string( $data )) {
```

**Comment by Jeckerson** [comment]
@jeijei4 Hello, could you submit the PR?

**Comment by niden** [comment]
Resolved in https://github.com/phalcon/phalcon/pull/225
