### ISSUE TITLE
Refactor Phalcon\Registry

### ISSUE THREAD

**Issue by niden** [phalcon/phalcon#31]
Refactor Phalcon\Registry

**Comment by niden** [comment]
@phalcon/core-team 

I am thinking of scrapping this whole class. It is pretty much a copy of the `Phalcon\Collection` but with `final` in front of each method declaration.

Since this will be a major version, deprecating components should be OK so long as we communicate this to the community.

Thoughts?

**Comment by Jeckerson** [comment]
Never used it. I'm ok with deprecation.

**Comment by zsilbi** [comment]
Me neither, so +1

**Comment by niden** [comment]
Ok then lol. This issue is closed - we will not keep the Registry object.
