### ISSUE TITLE
[BUG]: The "setDefault" method does not work for forms of type "text" with name "value"

### ISSUE THREAD

**Issue by hostbox2** [phalcon/phalcon#360]
The "setDefault" method does not work for forms of type "text" with name "value".

Example Form initialize:
```php
class notificationsEditForm extends Form {

        public function initialize($entity = null) {
...
            $value = new Text('value', array(
                'maxlength' => '20'
            ));
            $value->setDefault('10');
            $value->addValidators(array(new Between(array(
                'minimum' => -999999999,
                'maximum' => 999999999,
                'message' => 'The field is filled incorrectly',
            ))));
            $this->add($value);
...
        }
    }
``` 

Example Form in controller:
```php
$notificationsEditForm = new \dashboard\notificationsEditForm();
``` 

Example Form in view:
```php
<?=$notificationsEditForm->render('value')?>
``` 

As a result, the form is displayed, but it has no default value (just a blank field).

IF you rename the form, for example, call the field "valuer" - the default value is inserted

**Details**
 - Phalcon 5.2.2
 - PHP Version: 8.1.20
 - Operating System: Ubuntu 22.04.2 LTS
 - Server: Nginx + Apache

**Comment by hakimio** [comment]
Do you use the phalcon extension or PHP version of the framework which is still WIP?

**Comment by hostbox2** [comment]
Phalcon was compiled from source using instructions from here: https://docs.phalcon.io/5.0/en/installation#compile-from-sources (Compile From Sources section)

**Comment by hostbox2** [comment]
> Do you use the phalcon extension or PHP version of the framework which is still WIP?

Phalcon was compiled from source using instructions from here: https://docs.phalcon.io/5.0/en/installation#compile-from-sources (Compile From Sources section)

**Comment by hostbox2** [comment]
Compiling went without errors or problems. Clearly according to the instructions. And everything works fine in general, except for this bug

**Comment by hostbox2** [comment]
Installation was on a new clean system with the Hestia panel

**Comment by hakimio** [comment]
Then you are on the wrong github repo.
Issue tracker for phalcon extension: https://github.com/phalcon/cphalcon/issues
`phalcon/phalcon` is for the WIP cphalcon (phalcon PHP extension written in [zephir](https://github.com/zephir-lang/zephir)) port to pure PHP.
