### ISSUE TITLE
[BUG]: \Phalcon\Encryption\Crypt + named parameters/arguments throw fatal error.

### ISSUE THREAD

**Issue by victorshdev** [phalcon/phalcon#398]
Hello.

Does Phalcon 5 support skipping arguments with default values when passing named parameters/arguments (a PHP 8.0 feature)?

I've encountered a Fatal error:

```php
ArgumentCountError: \Phalcon\Encryption\Crypt::__construct(): 
Argument #1 ($cipher) must be passed explicitly, because the default value is not known
```

**To Reproduce**

```php
$crypt = new \Phalcon\Encryption\Crypt(useSigning: false); 
```

**Expected behavior**

No error.

**Screenshots**

![image](https://github.com/phalcon/phalcon/assets/131619111/1e6e8c47-a415-4a79-8c98-75dda8e1c576)

**Details**

-  Phalcon version: 5.3.1
-  PHP Version: 8.2.10 (installed from pecl)
-  Operating System: Debian GNU/Linux 12 (in docker)
-  Server: Apache

**Additional context**

It works if the cipher is set explicitly.  If this behavior is expected, please provide some information about it. 

Many thanks.

**Comment by Jeckerson** [comment]
Phalcon does not support named arguments as it is not implemented in Zephir. As Zephir developer, I can tell that there are no plans until end of this year to introduce support of named arguments.

But if you really want this feature, please submit new issue inside [zephir](https://github.com/zephir-lang/zephir) repository.
