### ISSUE TITLE
[NFR]: What is the purpose of this library？

### ISSUE THREAD

**Issue by zbindu** [phalcon/phalcon#410]
Hi, Can you explain what this library is used to be? I'm a little confused. Thanks.

**Comment by niden** [comment]
This is the next version of Phalcon (v6). We are converting the Zephir code from Phalcon v5 to PHP. 

It is not ready yet, since a few namespaces are missing but we plan on getting this ready this year.

**Comment by zbindu** [comment]
> This is the next version of Phalcon (v6). We are converting the Zephir code from Phalcon v5 to PHP.
> 
> It is not ready yet, since a few namespaces are missing but we plan on getting this ready this year.

Does this mean there will be a php version of phalcon in the future ? Will cphalcon still exist .

**Comment by niden** [comment]
Yes there will be a PHP version of Phalcon. A cphalcon will also exist where you will be able to load it on your web server and will accompany the PHP version, offering higher performance in areas of the framework that are slow
