### ISSUE TITLE
[NFR]: Set Controller & Action Suffix

### ISSUE THREAD

**Issue by ghost** [phalcon/phalcon#68]
Ability to set custom controller and action suffix like in cphalcon 4.1 if not implemented yet. For ``setControllerSuffix`` and ``setActionSuffix``

Example:
```php
$di->set('dispatcher', function() {
  $dp = new Dispatcher();
  $dp->setControllerSuffix('');
  $dp->setActionSuffix('');
  $dp->setDefaultNamespace('App\Controllers');
  return $dp;
}); #dispatcher
```

**Comment by Jeckerson** [comment]
This feature already exist in `4.1` and will exist in `5.0`.

https://github.com/phalcon/cphalcon/blob/3241d96e4bb01dc7746b74c9ce586250b8887c46/phalcon/Mvc/Dispatcher.zep#L186

Closing.
