### ISSUE TITLE
[NFR]: Refactor Phalcon\Mvc\View\Volt

### ISSUE THREAD

**Issue by Jeckerson** [phalcon/phalcon#90]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. I am always frustrated when [...]

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by quasipickle** [comment]
Now that Phalcon is moving to PHP-space, might this be a good time to transition away from Volt and to something more widespread - like Twig?

I realize v5 is intended to have parity with v4, so this might need to wait until v5.1 or v6, but I don't see the point of having Yet-Another-PHP-Template-Library that behaves very much like Twig.

**Comment by ghost** [comment]
No please don't do that. Volt is good enought! https://github.com/phalcon/phalcon/discussions/96

**Comment by Jeckerson** [comment]
@quasipickle Volt will continue to exist. It probably will be separated into own repository to add in project when you are using it, but in `v5` it will be bundled as it is in `v4`.

**Comment by niden** [comment]
Implemented https://github.com/phalcon/phalcon/pull/505
